---
- name: install node_exporter on rpi cluster nodes
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    rpi_hostnames: "{{ groups ['all'] | map ('extract', hostvars, ['ansible_hostname']) }}"
    rpi_addresses: "{{ groups ['all'] | map ('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
  
  tasks:

  - debug:
      msg: "{{ rpi_hostnames }}"
  
  - debug:
      msg: "{{ rpi_addresses }}"

  #roles:
  #  - install_node_exporter
