---
- name: install node_exporter on rpi cluster nodes
  hosts: all
  become: true
  gather_facts: true

  
  tasks:
  
  - name: make host group
    set_fact:
      rpi_hosts_group: "{{ansible_play_hosts}}"
  
  - debug:
      var: "{{rpi_hosts_group}}"
  
  #roles:
  #  - install_node_exporter
