---
- name: install node_exporter on rpi cluster nodes
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    rpi_nodes: "{{ groups ['all'] | map ('extract', hostvars, ['ansible_host']) }}"
  
  tasks:

  - debug:
      msg: "{{ rpi_nodes }}"

  #roles:
  #  - install_node_exporter
