---
# get the required rpi node variables for prometheus conifiguration 
#- name: set rpi node variables
#  set_fact:
#    rpi_hostnames: "{{ groups ['all'] | map ('extract', hostvars, ['ansible_hostname']) }}"
#    rpi_addresses: "{{ groups ['all'] | map ('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
#  delegate_to: localhost

# configure prometheus.yml
- name: update prometheus.yml configuration
  block:

  - name: create temp dir prometheus.d
    file:
      path: "{{ prometheus_config_dir }}/prometheus.d"
      state: directory

  - name: copy existing prometheus.yml
    copy:
      src: "{{ prometheus_config_dir }}/prometheus.yml"
      dest: "{{ prometheus_config_dir }}/prometheus.d/temp1.yml"
      remote_src: yes

  - name: copy new config to prometheus host
    template:
      src: prometheus.yml.j2
      dest: "{{ prometheus_config_dir }}/prometheus.d/temp2.yml"
  
  - name: assemble new config
    assemble:
      src: "{{ prometheus_config_dir }}/prometheus.d"
      #dest: "{{ prometheus_config_dir }}/prometheus.yml"
      dest: "{{ prometheus_config_dir }}/prometheus.d/prometheus.yml"
      backup: yes
  
  - name: remove temp config file
    file:
      path: "{{ prometheus_config_dir }}/prometheus.d"
      state: absent
    check_mode: yes

  # restart the prometheus container
  - name: restart prometheus
    docker_container:
      name: prometheus
      state: started
      restart: yes

  delegate_to: "{{ prometheus_host }}"

  

  

