---
# main tasks for prometheus configuration
- name: copy config to prometheus directory
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus2.yml"
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{ prometheus_host }}"
